# Generated by Django 3.2.4 on 2021-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
